apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginxapp
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
